[package]
name = "server-client"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
log = "0.4.21"
env_logger = "0.11.3"
sta-client = { path = "./sta-client" }
sta-server = { path = "./sta-server" }